### ISSUE TITLE
free smtp email

### ISSUE THREAD

**Issue by aliceinwire** [GKernelCI/Gdocker#15]
Gmail smtp is mostly unreliable on gmail. As most of the time mail gets blocked by the unreliable client un-feature.
We need a simple email for delivery build status email

**Comment by jessesimpson36** [comment]
You could consider a service like [mailpit](https://mailpit.axllent.org/), and add it into the docker-compose.yaml file
```
  mailpit:
    container_name: mailpit
    image: axllent/mailpit:${MAILPIT_VERSION}
    ports:
      - "1025:1025"
      - "8075:8025"
    healthcheck:
      test: /usr/bin/nc -v localhost 1025
      interval: 30s
```

The way mailpit works is it provides a UI that simulates sending+receiving emails.So when the GKCI project contacts mailpit over SMTP, mailpit just records the entry, and you can log into it to view what emails were sent.  It's not as useful as say, something that actually sends emails to you, but it is at least free and testable locally.

**Comment by aliceinwire** [comment]
mailpit looks interesting, never used it

**Comment by jessesimpson36** [comment]
as for mailpit, I just recently tried it out. 

Here is the snippet in `master.cfg`
```python
generator = reporters.BuildStatusGenerator(
    mode=('all'),
    message_formatter=reporters.MessageFormatter(
                               template=template, template_type='html',
                               want_properties=True, want_steps=True))
mn = reporters.MailNotifier(fromaddr="gkernelci@alicef.me",
                            sendToInterestedUsers=False,
                            extraRecipients=['alicef+gkernelci@gentoo.org',
                                             'gentoo@veremit.xyz'],
                            relayhost="mailpit",
                            smtpPort=1025, smtpUser="gkernelci@gkernelci.gentoo.org",
                            smtpPassword=os.environ.get('MAIL_PASSWORD'),
                            generators=[generator])

```

and snippet in `docker-compose.yml`

```
  mailpit:
    networks:
      - gkernelci-net
    container_name: mailpit
    image: axllent/mailpit:v1.20.7
    ports:
      - "1025:1025"
      - "8075:8025"
    healthcheck:
      test: /usr/bin/nc -v localhost 1025
      interval: 30s

```

One quirk about it is it does require an empty `MAIL_PASSWORD` in the buildbot service.

:

<img width="1897" height="1411" alt="Image" src="https://github.com/user-attachments/assets/1dbb93dd-abb8-487f-8698-d6a1c1a8586b" />

I'm not quite sure why it's not showing me more inside the steps.
